newscoop_tageswochemobile_plugin.default:
  resource: "@NewscoopTagesWocheMobilePluginBundle/Controller/DefaultController.php"
  type:     annotation
  prefix:   /mapi

newscoop_tageswochemobile_plugin.articles:
  resource: "@NewscoopTagesWocheMobilePluginBundle/Controller/ArticlesController.php"
  type:     annotation
  prefix:   /mapi/articles

newscoop_tageswochemobile_plugin.archive:
  resource: "@NewscoopTagesWocheMobilePluginBundle/Controller/ArchiveController.php"
  type:     annotation
  prefix:   /mapi/archive

newscoop_tageswochemobile_plugin.blogs:
  resource: "@NewscoopTagesWocheMobilePluginBundle/Controller/BlogsController.php"
  type:     annotation
  prefix:   /mapi/blogs

newscoop_tageswochemobile_plugin.comments:
  resource: "@NewscoopTagesWocheMobilePluginBundle/Controller/CommentsController.php"
  type:     annotation
  prefix:   /mapi/comments

newscoop_tageswochemobile_plugin.debates:
  resource: "@NewscoopTagesWocheMobilePluginBundle/Controller/DebatesController.php"
  type:     annotation
  prefix:   /mapi/debates

newscoop_tageswochemobile_plugin.topics:
  resource: "@NewscoopTagesWocheMobilePluginBundle/Controller/TopicsController.php"
  type:     annotation
  prefix:   /mapi/topics

newscoop_tageswochemobile_plugin.sections:
  resource: "@NewscoopTagesWocheMobilePluginBundle/Controller/SectionsController.php"
  type:     annotation
  prefix:   /mapi/sections

newscoop_tageswochemobile_plugin.profile:
  resource: "@NewscoopTagesWocheMobilePluginBundle/Controller/ProfileController.php"
  type:     annotation
  prefix:   /mapi/profile

newscoop_tageswochemobile_plugin.purchase:
  resource: "@NewscoopTagesWocheMobilePluginBundle/Controller/PurchaseController.php"
  type:     annotation
  prefix:   /mapi/purchase

newscoop_tageswochemobile_plugin.online:
  resource: "@NewscoopTagesWocheMobilePluginBundle/Controller/OnlineController.php"
  type:     annotation
  prefix:   /mapi/online

newscoop_tageswochemobile_plugin.offline:
  resource: "@NewscoopTagesWocheMobilePluginBundle/Controller/OfflineController.php"
  type:     annotation
  prefix:   /mapi/offline

newscoop_tageswochemobile_plugin.wheel-advertisement:
  resource: "@NewscoopTagesWocheMobilePluginBundle/Controller/WheelAdvertisementController.php"
  type:     annotation
  prefix:   /mapi/wheel-advertisement

newscoop_tageswochemobile_plugin.legal:
  resource: "@NewscoopTagesWocheMobilePluginBundle/Controller/LegalController.php"
  type:     annotation
  prefix:   /mapi/legal
